### PR TITLE
Exclusions of disallowed names, fixes #18

### LINKED ISSUE #18: Illegal variable name 'do' when splicing a TH declaration
```
shell-conduit> [6 of 7] Compiling Data.Conduit.Shell.PATH
shell-conduit>             
shell-conduit> /tmp/stack30820/shell-conduit-4.7.0/src/Data/Conduit/Shell/PATH.hs:29:3: error:
shell-conduit>     Illegal variable name: ‘do’
shell-conduit>     When splicing a TH declaration:
shell-conduit>       do = Data.Conduit.Shell.Variadic.variadicProcess "do"
shell-conduit>    |        
shell-conduit> 29 | $(generateBinaries)
```

Tested on stack resolver lts-14.27.

### PR DESCRIPTION
**Pull request by danwdart**

### CODE REVIEW

**Comment by psibi** [comment]
Thanks! Sorry, that it took more time to address this.

**Comment by danwdart** [comment]
No worries - thanks!

**Comment by danwdart** [comment]
Which release / when will this be included in Hackage / Stackage, btw?

**Comment by psibi** [comment]
@danwdart I'm planning to get https://github.com/psibi/shell-conduit/pull/17 merged and release a new version. If this is something you want quickly - I can release without it.

**Comment by danwdart** [comment]
Fair enough, well I'm not in a huge rush. Just curious. I have just pointed my stack dep in my project(s) to my fork for now.

Ta

**Comment by psibi** [comment]
@danwdart A new version has been uploaded to Hackage. Thanks for the patience!

**Comment by danwdart** [comment]
Great, thanks!

**Pull request merged**
